title = "Protein Report"
baseurl = "/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 10
rssLimit = 10
summarylength = 20 # 70 (default)
timeout = 600000
googleAnalytics = "G-KXVQT2THTT"

[params]
  hyas_images = false
  event_partners = true

copyRight = "Copyright (c) 2023 Protein Report"

[social]
  twitter = "Protein_Report"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "JSON", "SearchIndex" ]
section = [ "HTML", "RSS", "JSON" ]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "30m"

[taxonomies]
  category = "categories"
  protein = "proteins"
  product = "products"
  topic = "topics"
  region = "regions"
  flag = "flags"

[permalinks]
  blog = "/:title/"
  proteins = "/:slug/"
  products = "/:slug/"
  topics = "/:slug/"
  regions = "/:slug/"
  flags = "/:slug/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "tags"
    weight = 80
    [[related.indices]]
    name = "date"
    weight = 10

[imaging]
  anchor = 'Smart'
  bgColor = '#fff'
  hint = 'photo'
  quality = 90
  resampleFilter = 'Lanczos'

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$','^babel$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']